name: New Release

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly

    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Build binary
      run: cargo +nightly build --target x86_64-pc-windows-msvc --release

    - name: Package for release
      shell: pwsh
      run: |
        $ASSET_NAME = "shears-${{ github.ref_name }}.zip"
        $BINARY_PATH = "target/x86_64-pc-windows-msvc/release/shears.exe"
        Compress-Archive -Path $BINARY_PATH -DestinationPath $ASSET_NAME
        echo "ASSET_PATH=$ASSET_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ASSET_PATH }}