name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly

    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Check formatting
      run: cargo +nightly fmt --all -- --check

    - name: Run clippy
      run: cargo +nightly clippy --all -- -D warnings